services:
  db:
    image: postgres:16
    container_name: kc-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
    ports:
      - "16432:5432"
    volumes:
      - ./keycloak/kc-db-data/data:/var/lib/postgresql/data
      - ./keycloak/kc-db-data/app:/app
    working_dir: /app

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    # build:
    #   context: ./keycloak
    container_name: kc-server
    ports:
      - "18080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 1q2w3e
    depends_on:
      - db
    command: >
      start-dev
      --features=hostname:v2
      --hostname-strict=false
      --http-enabled=true
      --hostname=localhost

networks:
  default:
    name: keycloak-net
